### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by vusy-nathan** [GraseHotspot/grase-www-portal#121]
hi
i just installed the night build on ubuntu 12.04 server 

after all it just shows a blank page

**Comment by vusy-nathan** [comment]
also i noticed when i installed the i got 

cat: /etc/dnsmasq.d/01-grasehotspot: No such file or directory

**Comment by purewhite2010** [comment]
Please post support requests to the mailing list. You'll need to show Apache/PHP error logs to assist with debugging this
