### ISSUE TITLE
Ability to create cutom default data and time limits for groups

### ISSUE THREAD

**Issue by makarabeach** [GraseHotspot/grase-www-portal#141]
Currently the data and time limits that can be applied to groups appear to be hard coded. It would be great to have the ability to add custom values to the limits, or have a larger list of limits available in increments of 10GB, so for example we can set a recurring monthly limit of 20Gb.

**Comment by timwhite** [comment]
@makarabeach This is currently already possible. Look in the Settings page, space separated list of Data Options is what you are looking for. 
Suggestions for how to best implement this in the future are welcome.

**Comment by makarabeach** [comment]
Thanks Tim

 

I had been using an older version of Grase and hadn’t caught up with this change, so thanks very much!

 

 

Regards

 

 

David
