### ISSUE TITLE
Setup Patreon grasehotspot.org

### ISSUE THREAD

**Issue by Ark74** [GraseHotspot/grase-www-portal#168]
Hi!

This week i was checking the message about supporting the development to convert Grasehotspot development more serious (paid) work.

I'm all into it, with that in mind i would suggest a to add a Support Development page kind of like a Patreon page, since the current Donation page really needs to be more explicit about paid development.
There are deployments all over the world with hundreds maybe thousands of users and i'm sure that they would love to contribute too.

And for all the ambulant users that come and go, knowing that they could have a supported platform i believe it would be valuable.

**Comment by timwhite** [comment]
Thanks for the suggestion @Ark74. I'll look at setting one up shortly. Maybe I'll try and revamp the website at the same time to be cleaner, easier to find information, and more obvious about how to support development

**Comment by timwhite** [comment]
I've setup a Patreon page. Feedback is welcomed.
https://www.patreon.com/grase

**Comment by Ark74** [comment]
Just joined via Paypal, so no patreon badge for me. :disappointed:  :wink: 

The Patreon goals look great, please inform our friends at the mailing list, these are great news for the project. 

Cheers! :beers:

**Comment by timwhite** [comment]
@Ark74 Thanks for contributing anyway! This ticket should be reworded a little, as I intend to setup my own payment gateway as well, once I work out the best way to communicate to supporters with it. It'll most likely be via Stripe.

**Comment by Ark74** [comment]
Just leaving a note: 
https://donorbox.org

**Comment by timwhite** [comment]
Closing this as we now have recurring donations through the website. Donorbox is a great option, and would have no fee's for our current donation level, but was suggested a little too late.
