### ISSUE TITLE
no install

### ISSUE THREAD

**Issue by Cyberscitymaste** [GraseHotspot/grase-www-portal#172]
cant install everytime
wget http://nightly.packages.grasehotspot.org/pool/main/g/grase-repo/grase-repo_1.5_all.deb
--2018-01-12 22:24:05--  http://nightly.packages.grasehotspot.org/pool/main/g/grase-repo/grase-repo_1.5_all.deb
Auflösen des Hostnamen »nightly.packages.grasehotspot.org (nightly.packages.grasehotspot.org)«... 2600:3c00::20:c00f, 66.228.55.48
Verbindungsaufbau zu nightly.packages.grasehotspot.org (nightly.packages.grasehotspot.org)|2600:3c00::20:c00f|:80...

every time No connect allowed

**Comment by Ark74** [comment]
Seems to be a server issue. Let's wait, maybe its under maintenance.
Cheers!

**Comment by timwhite** [comment]
It should be fixed now. Let me know if it's not working.

Tim
