### ISSUE TITLE
Updated install instructions

### ISSUE THREAD

**Issue by i80486sx** [GraseHotspot/grase-www-portal#175]
Are there updated instructions for installing this product with Ubuntu 16 or 18?  I would like to try out Grasespot, but I'm getting the error below when installing grasespot.

ase-conf-openvpn
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 grase-conf-freeradius : Depends: dbconfig-common but it is not installable
                         Depends: libconfig-simple-perl but it is not installable
                         Depends: libxml-simple-perl but it is not installable
                         Depends: libtime-modules-perl but it is not installable
                         PreDepends: freeradius but it is not going to be installed
                         PreDepends: freeradius-mysql but it is not going to be installed
                         PreDepends: coova-chilli (>= 1.3.0) but it is not going to be installed
 grase-conf-openvpn : Depends: openvpn but it is not going to be installed
                      Recommends: ntp but it is not going to be installed
 grase-www-portal : Depends: php-mdb2-driver-mysql but it is not installable
                    Depends: php-mdb2 but it is not installable
                    Depends: php-auth but it is not installable
                    Depends: php-gettext but it is not installable
                    Depends: javascript-common but it is not installable
                    Depends: dbconfig-common but it is not installable
E: Unable to correct problems, you have held broken packages.

I've attempted to use Ubuntu Server 12, 14, 16 and 18 LTS.  I've used both 32 and 64 bit versions.

**Comment by timwhite** [comment]
Please use the mailing list for support (https://grasehotspot.org/support/mailing-list/)

Ubuntu 14.04 should be working, as should Debian 8 (see https://grasehotspot.org/documentation/known-issues/ for a Debian 8 issue and how to fix it)

I am working on bringing everything up to date to support 18.04, however it's not expected to be complete until the end of the year due to time constraints.
