### ISSUE TITLE
after Upgrade and dist-Upgrade

### ISSUE THREAD

**Issue by Cyberscitymaste** [GraseHotspot/grase-www-portal#177]
Hallo after apt-get update & apt-upgrade my grase dont work no connect no web interface i become many many errors can you tell me i try in german darf man kein update bzw dist update machen nach der installation ich hatte versucht upzudaten um die deutschen sprach files zu bekommen den ich hatte alles in englisch trotz das deutsch eingestellt war

if you need log please tell me what you need iam not expert in englisch

**Comment by timwhite** [comment]
As stated on the Contact page, please post support requests to the mailing list.
https://grasehotspot.org/support/mailing-list/
If you need to collect installation information to accompany your support request, please read https://grasehotspot.org/support/collecting-support-information/
