### ISSUE TITLE
Ability to disconnect active users (Trac #28)

### ISSUE THREAD

**Issue by timwhite** [GraseHotspot/grase-www-portal#28]
Coova Chilli provides the ability to disconnect a session via the coaport. We need to make this usable from the web interface.

The following is from the mailing list, maybe we can make it more secure than this? Sudo shouldn't be needed for radclient.

>1. first edit /etc/init.d/chilli to add listen port for disconnect packet by adding the line
>DAEMON_ARGS="--coaport 3779"
>
>so the first line would be like this:
>#! /bin/sh
>PATH=/sbin:/bin:/usr/sbin:/usr/bin
>DAEMON=/usr/sbin/chilli
>NAME=chilli
>DESC=chilli
>DAEMON_ARGS="--coaport 3779"
>
>2. add coaport on /etc/chilli/hs.conf or in
>
># TAG COA Port
>coaport 3779
>
>3. restart chilli
>
>4. Don't forget to add sudo line to allow www-data permission on /etc/sudoers
>www-data ALL=NOPASSWD:/bin/echo
>www-data ALL=NOPASSWD:/usr/bin/radclient
>
>
>5. test it first, try execute this in shellcommand
>echo "User-Name=username" | radclient -x 127.0.0.1:3779 disconnect yourradiussecret
>
>username is the username who want you kick out from grase.
>yourradiussecret is radius secret, if u did not change it, the deflaut from grase is >hotspotradius
>
>6. or u can use php sript. (example)
>$shell_command='sudo /bin/echo "User-Name='.kevin.'" | /usr/bin/radclient -x 127.0.0.1:3779 >disconnect hotspotradius ';
>$output = shell_exec($shell_command);
>
>

Migrated from http://trac.grasehotspot.org/ticket/28
```json
{
    "status": "new", 
    "changetime": "2011-08-31T22:41:13", 
    "description": "Coova Chilli provides the ability to disconnect a session via the coaport. We need to make this usable from the web interface.\n\nThe following is from the mailing list, maybe we can make it more secure than this? Sudo shouldn't be needed for radclient.\n\n>1. first edit /etc/init.d/chilli to add listen port for disconnect packet by adding the line\n>DAEMON_ARGS=\"--coaport 3779\"\n>\n>so the first line would be like this:\n>#! /bin/sh\n>PATH=/sbin:/bin:/usr/sbin:/usr/bin\n>DAEMON=/usr/sbin/chilli\n>NAME=chilli\n>DESC=chilli\n>DAEMON_ARGS=\"--coaport 3779\"\n>\n>2. add coaport on /etc/chilli/hs.conf or in\n>\n># TAG COA Port\n>coaport 3779\n>\n>3. restart chilli\n>\n>4. Don't forget to add sudo line to allow www-data permission on /etc/sudoers\n>www-data ALL=NOPASSWD:/bin/echo\n>www-data ALL=NOPASSWD:/usr/bin/radclient\n>\n>\n>5. test it first, try execute this in shellcommand\n>echo \"User-Name=username\" | radclient -x 127.0.0.1:3779 disconnect yourradiussecret\n>\n>username is the username who want you kick out from grase.\n>yourradiussecret is radius secret, if u did not change it, the deflaut from grase is >hotspotradius\n>\n>6. or u can use php sript. (example)\n>$shell_command='sudo /bin/echo \"User-Name='.kevin.'\" | /usr/bin/radclient -x 127.0.0.1:3779 >disconnect hotspotradius ';\n>$output = shell_exec($shell_command);\n>\n>", 
    "reporter": "tim", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1314830473155211", 
    "component": "Admin Interface", 
    "summary": "Ability to disconnect active users", 
    "priority": "major", 
    "keywords": "coaport, disconnect, active, session", 
    "version": "3.4", 
    "time": "2011-08-31T22:39:48", 
    "milestone": "4.0", 
    "owner": "tim", 
    "type": "enhancement"
}
```

**Comment by purewhite2010** [comment]
We currently just use the coova_query command to do this from the sessions page
