### ISSUE TITLE
Translation of forms and other uam functions are slow due to loading libs (Trac #74)

### ISSUE THREAD

**Issue by ghost** [GraseHotspot/grase-www-portal#74]
Most php scripts in uam have require_once('includes/site.inc.php') at the start. This is needed to load settings and to be able to translate files, etc.

Find a way to lighten this considerably, as each request has 300ms of overhead just loading all the libraries!

Possibility, as most of them are just for translation of templates, to write a new light template translator that we pass the language to in the GET request, so no loading of libs to read settings is needed, and we just need the translation code. Check if Smarty is still good if we are just doing translations, or if a quicker method is available.

Migrated from http://trac.grasehotspot.org/ticket/74

``` json
{
    "status": "accepted", 
    "changetime": "2012-06-28T03:24:04", 
    "description": "Most php scripts in uam have require_once('includes/site.inc.php') at the start. This is needed to load settings and to be able to translate files, etc.\n\nFind a way to lighten this considerably, as each request has 300ms of overhead just loading all the libraries!\n\nPossibility, as most of them are just for translation of templates, to write a new light template translator that we pass the language to in the GET request, so no loading of libs to read settings is needed, and we just need the translation code. Check if Smarty is still good if we are just doing translations, or if a quicker method is available.", 
    "reporter": "tim", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1340853844746335", 
    "component": "Splash Screens", 
    "summary": "Translation of forms and other uam functions are slow due to loading libs", 
    "priority": "minor", 
    "keywords": "", 
    "version": "3.7", 
    "time": "2012-06-28T03:23:54", 
    "milestone": "3.9", 
    "owner": "tim", 
    "type": "enhancement"
}
```

**Comment by timwhite** [comment]
Translations now occur both in PHP and JS solving this
